import {
  ClerkProvider,
  SignInButton,
  SignedIn,
  SignedOut,
  UserButton
} from '@clerk/nextjs'
import './globals.css'
import type { Metadata } from "next";

export const metadata: Metadata = {
    title: "Clerk | Authenication & Authorization",
    description: "Generated by create next app",
  };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ClerkProvider>
      <html lang="en">
        <body>
          <SignedOut>
            <div className='max-w-full bg-gradient-to-r from-yellow-500 to-green-600'>
              <div className='flex justify-end items-end text-left font-bold max-w-[1440px] text-white hover:text-black py-2 '>
                <SignInButton/>
              </div>
            </div>
            
          </SignedOut>
          <SignedIn>
           <div className='max-w-full bg-gradient-to-r from-yellow-500 to-green-600'>
           <div className='flex justify-end items-end text-left font-bold max-w-[1440px] text-white hover:text-black '>
                <UserButton />
              </div>
            </div>
            
          </SignedIn>
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}

