import type { Metadata } from "next";
import "./globals.css";
import { inter } from '../app/ui/font';
import {montserrat} from '../app/ui/font';
import {Toaster} from 'sonner'



export const metadata: Metadata = {
  title: "Portfolio | OsamabinAdnan",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      
      <body
        className={` ${inter.className} ${montserrat.className} antialiased overflow-auto`}
      >
        {children}
        <Toaster expand={false} position="top-right" richColors/>
      </body>
      
    </html>
  );
}
